// flow-typed signature: a0a4e9ec8709037554c1293aeb89bfa6
// flow-typed version: <<STUB>>/ci-publish_v^1.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ci-publish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ci-publish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ci-publish/bin/ci-publish' {
  declare module.exports: any;
}

declare module 'ci-publish/src/commits-since-last-release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ci-publish/bin/ci-publish.js' {
  declare module.exports: $Exports<'ci-publish/bin/ci-publish'>;
}
declare module 'ci-publish/src/commits-since-last-release.js' {
  declare module.exports: $Exports<'ci-publish/src/commits-since-last-release'>;
}
