// flow-typed signature: f5c29bf27030ed787a157d4cbfd3283e
// flow-typed version: <<STUB>>/execa_v^0.6.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'execa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'execa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'execa/lib/errname' {
  declare module.exports: any;
}

// Filename aliases
declare module 'execa/index' {
  declare module.exports: $Exports<'execa'>;
}
declare module 'execa/index.js' {
  declare module.exports: $Exports<'execa'>;
}
declare module 'execa/lib/errname.js' {
  declare module.exports: $Exports<'execa/lib/errname'>;
}
