// flow-typed signature: e5358fbb5c16900a83634d77d9837c88
// flow-typed version: <<STUB>>/input_v^1.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'input/dist/lib/finaliseOptions' {
  declare module.exports: any;
}

declare module 'input/dist/lib/index' {
  declare module.exports: any;
}

declare module 'input/dist/lib/processDoubleArgs' {
  declare module.exports: any;
}

declare module 'input/dist/lib/processTripleArgs' {
  declare module.exports: any;
}

declare module 'input/dist/lib/Prompt' {
  declare module.exports: any;
}

declare module 'input/src/lib/finaliseOptions' {
  declare module.exports: any;
}

declare module 'input/src/lib/index' {
  declare module.exports: any;
}

declare module 'input/src/lib/processDoubleArgs' {
  declare module.exports: any;
}

declare module 'input/src/lib/processTripleArgs' {
  declare module.exports: any;
}

declare module 'input/src/lib/Prompt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'input/dist/lib/finaliseOptions.js' {
  declare module.exports: $Exports<'input/dist/lib/finaliseOptions'>;
}
declare module 'input/dist/lib/index.js' {
  declare module.exports: $Exports<'input/dist/lib/index'>;
}
declare module 'input/dist/lib/processDoubleArgs.js' {
  declare module.exports: $Exports<'input/dist/lib/processDoubleArgs'>;
}
declare module 'input/dist/lib/processTripleArgs.js' {
  declare module.exports: $Exports<'input/dist/lib/processTripleArgs'>;
}
declare module 'input/dist/lib/Prompt.js' {
  declare module.exports: $Exports<'input/dist/lib/Prompt'>;
}
declare module 'input/src/lib/finaliseOptions.js' {
  declare module.exports: $Exports<'input/src/lib/finaliseOptions'>;
}
declare module 'input/src/lib/index.js' {
  declare module.exports: $Exports<'input/src/lib/index'>;
}
declare module 'input/src/lib/processDoubleArgs.js' {
  declare module.exports: $Exports<'input/src/lib/processDoubleArgs'>;
}
declare module 'input/src/lib/processTripleArgs.js' {
  declare module.exports: $Exports<'input/src/lib/processTripleArgs'>;
}
declare module 'input/src/lib/Prompt.js' {
  declare module.exports: $Exports<'input/src/lib/Prompt'>;
}
