// flow-typed signature: 1b60982c14f87eded679ec3cc1348ccd
// flow-typed version: <<STUB>>/npm-cli-login_v0.0.10/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-cli-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-cli-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-cli-login/bin/npm-cli-login' {
  declare module.exports: any;
}

declare module 'npm-cli-login/lib/index' {
  declare module.exports: any;
}

declare module 'npm-cli-login/lib/login' {
  declare module.exports: any;
}

declare module 'npm-cli-login/tests/internal.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-cli-login/bin/npm-cli-login.js' {
  declare module.exports: $Exports<'npm-cli-login/bin/npm-cli-login'>;
}
declare module 'npm-cli-login/index' {
  declare module.exports: $Exports<'npm-cli-login'>;
}
declare module 'npm-cli-login/index.js' {
  declare module.exports: $Exports<'npm-cli-login'>;
}
declare module 'npm-cli-login/lib/index.js' {
  declare module.exports: $Exports<'npm-cli-login/lib/index'>;
}
declare module 'npm-cli-login/lib/login.js' {
  declare module.exports: $Exports<'npm-cli-login/lib/login'>;
}
declare module 'npm-cli-login/tests/internal.spec.js' {
  declare module.exports: $Exports<'npm-cli-login/tests/internal.spec'>;
}
