// flow-typed signature: 5b73e711dc6d71a609f68d1b87cbe8d3
// flow-typed version: <<STUB>>/parse-github-url_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-github-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-github-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-github-url/index' {
  declare module.exports: $Exports<'parse-github-url'>;
}
declare module 'parse-github-url/index.js' {
  declare module.exports: $Exports<'parse-github-url'>;
}
