// flow-typed signature: 85bf60a35ebc9753b99a1e3ed3bbd765
// flow-typed version: <<STUB>>/parse-github-url_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-github-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-github-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-github-url/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-github-url/cli.js' {
  declare module.exports: $Exports<'parse-github-url/cli'>;
}
declare module 'parse-github-url/index' {
  declare module.exports: $Exports<'parse-github-url'>;
}
declare module 'parse-github-url/index.js' {
  declare module.exports: $Exports<'parse-github-url'>;
}
