// flow-typed signature: dfd8459b1dfe43370f95d5e926f6a00a
// flow-typed version: <<STUB>>/tmp-promise_v^1.0.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp-promise/example-usage' {
  declare module.exports: any;
}

declare module 'tmp-promise/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp-promise/example-usage.js' {
  declare module.exports: $Exports<'tmp-promise/example-usage'>;
}
declare module 'tmp-promise/index' {
  declare module.exports: $Exports<'tmp-promise'>;
}
declare module 'tmp-promise/index.js' {
  declare module.exports: $Exports<'tmp-promise'>;
}
declare module 'tmp-promise/test.js' {
  declare module.exports: $Exports<'tmp-promise/test'>;
}
